// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerUrlDev defines the Server URL for Dev
const ServerUrlDev = "/api/v1"

// ServerUrlProd defines the Server URL for Prod
const ServerUrlProd = "/api/v1"

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Leave a slam
	// (DELETE /participations/slams/{slamID})
	DeleteParticipationsSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string)
	// Join a slam
	// (POST /participations/slams/{slamID})
	PostParticipationsSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string)
	// Get users for a slam
	// (GET /participations/slams/{slamID}/users)
	GetParticipationsSlamsSlamIDUsers(w http.ResponseWriter, r *http.Request, slamID string, params GetParticipationsSlamsSlamIDUsersParams)
	// Add user to a slam
	// (POST /participations/slams/{slamID}/users)
	PostParticipationsSlamsSlamIDUsers(w http.ResponseWriter, r *http.Request, slamID string)
	// Remove participant
	// (DELETE /participations/slams/{slamID}/users/{userID})
	DeleteParticipationsSlamsSlamIDUsersUserID(w http.ResponseWriter, r *http.Request, slamID string, userID string)
	// Edit participant
	// (PUT /participations/slams/{slamID}/users/{userID})
	PutParticipationsSlamsSlamIDUsersUserID(w http.ResponseWriter, r *http.Request, slamID string, userID string)
	// Get slams for a user
	// (GET /participations/users/{userID}/slams)
	GetParticipationsUsersUserIDSlams(w http.ResponseWriter, r *http.Request, userID string, params GetParticipationsUsersUserIDSlamsParams)
	// Delete a performance
	// (DELETE /performances/{performanceID})
	DeletePerformancesPerformanceID(w http.ResponseWriter, r *http.Request, performanceID string)
	// Get a performance
	// (GET /performances/{performanceID})
	GetPerformancesPerformanceID(w http.ResponseWriter, r *http.Request, performanceID string)
	// Update a performance
	// (PUT /performances/{performanceID})
	PutPerformancesPerformanceID(w http.ResponseWriter, r *http.Request, performanceID string)
	// Get votes for performance
	// (GET /performances/{performanceID}/votes)
	GetPerformancesPerformanceIDVotes(w http.ResponseWriter, r *http.Request, performanceID string, params GetPerformancesPerformanceIDVotesParams)
	// Cast a vote for a performance
	// (POST /performances/{performanceID}/votes)
	PostPerformancesPerformanceIDVotes(w http.ResponseWriter, r *http.Request, performanceID string)
	// Get all slams
	// (GET /slams)
	GetSlams(w http.ResponseWriter, r *http.Request, params GetSlamsParams)
	// Create a slam
	// (POST /slams)
	PostSlams(w http.ResponseWriter, r *http.Request)
	// Delete a slam
	// (DELETE /slams/{slamID})
	DeleteSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string)
	// Get slam by ID
	// (GET /slams/{slamID})
	GetSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string)
	// Update a slam
	// (PUT /slams/{slamID})
	PutSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string)
	// List stages for a slam
	// (GET /slams/{slamID}/stages)
	GetSlamsSlamIDStages(w http.ResponseWriter, r *http.Request, slamID string, params GetSlamsSlamIDStagesParams)
	// Create a new stage for a slam
	// (POST /slams/{slamID}/stages)
	PostSlamsSlamIDStages(w http.ResponseWriter, r *http.Request, slamID string)
	// Delete a stage
	// (DELETE /stages/{stageID})
	DeleteStagesStageID(w http.ResponseWriter, r *http.Request, stageID string)
	// Get a stage
	// (GET /stages/{stageID})
	GetStagesStageID(w http.ResponseWriter, r *http.Request, stageID string)
	// Update stage
	// (PUT /stages/{stageID})
	PutStagesStageID(w http.ResponseWriter, r *http.Request, stageID string)
	// List performances for a stage
	// (GET /stages/{stageID}/performances)
	GetStagesStageIDPerformances(w http.ResponseWriter, r *http.Request, stageID string, params GetStagesStageIDPerformancesParams)
	// Add a performance to a stage
	// (POST /stages/{stageID}/performances)
	PostStagesStageIDPerformances(w http.ResponseWriter, r *http.Request, stageID string)
	// Update opponents
	// (PUT /stages/{stageID}/performances)
	PutStagesStageIDPerformances(w http.ResponseWriter, r *http.Request, stageID string)
	// Get all users
	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request, params GetUsersParams)
	// Add a new temporary user
	// (POST /users)
	PostUsers(w http.ResponseWriter, r *http.Request)
	// Delete a user
	// (DELETE /users/{userID})
	DeleteUsersUserID(w http.ResponseWriter, r *http.Request, userID string)
	// Get a user by ID
	// (GET /users/{userID})
	GetUsersUserID(w http.ResponseWriter, r *http.Request, userID string)
	// Update a user
	// (PUT /users/{userID})
	PutUsersUserID(w http.ResponseWriter, r *http.Request, userID string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Authenticate user
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Leave a slam
// (DELETE /participations/slams/{slamID})
func (_ Unimplemented) DeleteParticipationsSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Join a slam
// (POST /participations/slams/{slamID})
func (_ Unimplemented) PostParticipationsSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get users for a slam
// (GET /participations/slams/{slamID}/users)
func (_ Unimplemented) GetParticipationsSlamsSlamIDUsers(w http.ResponseWriter, r *http.Request, slamID string, params GetParticipationsSlamsSlamIDUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add user to a slam
// (POST /participations/slams/{slamID}/users)
func (_ Unimplemented) PostParticipationsSlamsSlamIDUsers(w http.ResponseWriter, r *http.Request, slamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove participant
// (DELETE /participations/slams/{slamID}/users/{userID})
func (_ Unimplemented) DeleteParticipationsSlamsSlamIDUsersUserID(w http.ResponseWriter, r *http.Request, slamID string, userID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Edit participant
// (PUT /participations/slams/{slamID}/users/{userID})
func (_ Unimplemented) PutParticipationsSlamsSlamIDUsersUserID(w http.ResponseWriter, r *http.Request, slamID string, userID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get slams for a user
// (GET /participations/users/{userID}/slams)
func (_ Unimplemented) GetParticipationsUsersUserIDSlams(w http.ResponseWriter, r *http.Request, userID string, params GetParticipationsUsersUserIDSlamsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a performance
// (DELETE /performances/{performanceID})
func (_ Unimplemented) DeletePerformancesPerformanceID(w http.ResponseWriter, r *http.Request, performanceID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a performance
// (GET /performances/{performanceID})
func (_ Unimplemented) GetPerformancesPerformanceID(w http.ResponseWriter, r *http.Request, performanceID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a performance
// (PUT /performances/{performanceID})
func (_ Unimplemented) PutPerformancesPerformanceID(w http.ResponseWriter, r *http.Request, performanceID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get votes for performance
// (GET /performances/{performanceID}/votes)
func (_ Unimplemented) GetPerformancesPerformanceIDVotes(w http.ResponseWriter, r *http.Request, performanceID string, params GetPerformancesPerformanceIDVotesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cast a vote for a performance
// (POST /performances/{performanceID}/votes)
func (_ Unimplemented) PostPerformancesPerformanceIDVotes(w http.ResponseWriter, r *http.Request, performanceID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all slams
// (GET /slams)
func (_ Unimplemented) GetSlams(w http.ResponseWriter, r *http.Request, params GetSlamsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a slam
// (POST /slams)
func (_ Unimplemented) PostSlams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a slam
// (DELETE /slams/{slamID})
func (_ Unimplemented) DeleteSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get slam by ID
// (GET /slams/{slamID})
func (_ Unimplemented) GetSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a slam
// (PUT /slams/{slamID})
func (_ Unimplemented) PutSlamsSlamID(w http.ResponseWriter, r *http.Request, slamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List stages for a slam
// (GET /slams/{slamID}/stages)
func (_ Unimplemented) GetSlamsSlamIDStages(w http.ResponseWriter, r *http.Request, slamID string, params GetSlamsSlamIDStagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new stage for a slam
// (POST /slams/{slamID}/stages)
func (_ Unimplemented) PostSlamsSlamIDStages(w http.ResponseWriter, r *http.Request, slamID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a stage
// (DELETE /stages/{stageID})
func (_ Unimplemented) DeleteStagesStageID(w http.ResponseWriter, r *http.Request, stageID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a stage
// (GET /stages/{stageID})
func (_ Unimplemented) GetStagesStageID(w http.ResponseWriter, r *http.Request, stageID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update stage
// (PUT /stages/{stageID})
func (_ Unimplemented) PutStagesStageID(w http.ResponseWriter, r *http.Request, stageID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List performances for a stage
// (GET /stages/{stageID}/performances)
func (_ Unimplemented) GetStagesStageIDPerformances(w http.ResponseWriter, r *http.Request, stageID string, params GetStagesStageIDPerformancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a performance to a stage
// (POST /stages/{stageID}/performances)
func (_ Unimplemented) PostStagesStageIDPerformances(w http.ResponseWriter, r *http.Request, stageID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update opponents
// (PUT /stages/{stageID}/performances)
func (_ Unimplemented) PutStagesStageIDPerformances(w http.ResponseWriter, r *http.Request, stageID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all users
// (GET /users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request, params GetUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new temporary user
// (POST /users)
func (_ Unimplemented) PostUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user
// (DELETE /users/{userID})
func (_ Unimplemented) DeleteUsersUserID(w http.ResponseWriter, r *http.Request, userID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user by ID
// (GET /users/{userID})
func (_ Unimplemented) GetUsersUserID(w http.ResponseWriter, r *http.Request, userID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user
// (PUT /users/{userID})
func (_ Unimplemented) PutUsersUserID(w http.ResponseWriter, r *http.Request, userID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteParticipationsSlamsSlamID operation middleware
func (siw *ServerInterfaceWrapper) DeleteParticipationsSlamsSlamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteParticipationsSlamsSlamID(w, r, slamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostParticipationsSlamsSlamID operation middleware
func (siw *ServerInterfaceWrapper) PostParticipationsSlamsSlamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostParticipationsSlamsSlamID(w, r, slamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetParticipationsSlamsSlamIDUsers operation middleware
func (siw *ServerInterfaceWrapper) GetParticipationsSlamsSlamIDUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetParticipationsSlamsSlamIDUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetParticipationsSlamsSlamIDUsers(w, r, slamID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostParticipationsSlamsSlamIDUsers operation middleware
func (siw *ServerInterfaceWrapper) PostParticipationsSlamsSlamIDUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostParticipationsSlamsSlamIDUsers(w, r, slamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteParticipationsSlamsSlamIDUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) DeleteParticipationsSlamsSlamIDUsersUserID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteParticipationsSlamsSlamIDUsersUserID(w, r, slamID, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutParticipationsSlamsSlamIDUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) PutParticipationsSlamsSlamIDUsersUserID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutParticipationsSlamsSlamIDUsersUserID(w, r, slamID, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetParticipationsUsersUserIDSlams operation middleware
func (siw *ServerInterfaceWrapper) GetParticipationsUsersUserIDSlams(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetParticipationsUsersUserIDSlamsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetParticipationsUsersUserIDSlams(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePerformancesPerformanceID operation middleware
func (siw *ServerInterfaceWrapper) DeletePerformancesPerformanceID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "performanceID" -------------
	var performanceID string

	err = runtime.BindStyledParameterWithOptions("simple", "performanceID", chi.URLParam(r, "performanceID"), &performanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePerformancesPerformanceID(w, r, performanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPerformancesPerformanceID operation middleware
func (siw *ServerInterfaceWrapper) GetPerformancesPerformanceID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "performanceID" -------------
	var performanceID string

	err = runtime.BindStyledParameterWithOptions("simple", "performanceID", chi.URLParam(r, "performanceID"), &performanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPerformancesPerformanceID(w, r, performanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPerformancesPerformanceID operation middleware
func (siw *ServerInterfaceWrapper) PutPerformancesPerformanceID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "performanceID" -------------
	var performanceID string

	err = runtime.BindStyledParameterWithOptions("simple", "performanceID", chi.URLParam(r, "performanceID"), &performanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPerformancesPerformanceID(w, r, performanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPerformancesPerformanceIDVotes operation middleware
func (siw *ServerInterfaceWrapper) GetPerformancesPerformanceIDVotes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "performanceID" -------------
	var performanceID string

	err = runtime.BindStyledParameterWithOptions("simple", "performanceID", chi.URLParam(r, "performanceID"), &performanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPerformancesPerformanceIDVotesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPerformancesPerformanceIDVotes(w, r, performanceID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPerformancesPerformanceIDVotes operation middleware
func (siw *ServerInterfaceWrapper) PostPerformancesPerformanceIDVotes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "performanceID" -------------
	var performanceID string

	err = runtime.BindStyledParameterWithOptions("simple", "performanceID", chi.URLParam(r, "performanceID"), &performanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "performanceID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPerformancesPerformanceIDVotes(w, r, performanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSlams operation middleware
func (siw *ServerInterfaceWrapper) GetSlams(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSlamsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSlams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSlams operation middleware
func (siw *ServerInterfaceWrapper) PostSlams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSlams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSlamsSlamID operation middleware
func (siw *ServerInterfaceWrapper) DeleteSlamsSlamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSlamsSlamID(w, r, slamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSlamsSlamID operation middleware
func (siw *ServerInterfaceWrapper) GetSlamsSlamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSlamsSlamID(w, r, slamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSlamsSlamID operation middleware
func (siw *ServerInterfaceWrapper) PutSlamsSlamID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSlamsSlamID(w, r, slamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSlamsSlamIDStages operation middleware
func (siw *ServerInterfaceWrapper) GetSlamsSlamIDStages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSlamsSlamIDStagesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSlamsSlamIDStages(w, r, slamID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSlamsSlamIDStages operation middleware
func (siw *ServerInterfaceWrapper) PostSlamsSlamIDStages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slamID" -------------
	var slamID string

	err = runtime.BindStyledParameterWithOptions("simple", "slamID", chi.URLParam(r, "slamID"), &slamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slamID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSlamsSlamIDStages(w, r, slamID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStagesStageID operation middleware
func (siw *ServerInterfaceWrapper) DeleteStagesStageID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "stageID" -------------
	var stageID string

	err = runtime.BindStyledParameterWithOptions("simple", "stageID", chi.URLParam(r, "stageID"), &stageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stageID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStagesStageID(w, r, stageID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStagesStageID operation middleware
func (siw *ServerInterfaceWrapper) GetStagesStageID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "stageID" -------------
	var stageID string

	err = runtime.BindStyledParameterWithOptions("simple", "stageID", chi.URLParam(r, "stageID"), &stageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stageID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStagesStageID(w, r, stageID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutStagesStageID operation middleware
func (siw *ServerInterfaceWrapper) PutStagesStageID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "stageID" -------------
	var stageID string

	err = runtime.BindStyledParameterWithOptions("simple", "stageID", chi.URLParam(r, "stageID"), &stageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stageID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutStagesStageID(w, r, stageID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStagesStageIDPerformances operation middleware
func (siw *ServerInterfaceWrapper) GetStagesStageIDPerformances(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "stageID" -------------
	var stageID string

	err = runtime.BindStyledParameterWithOptions("simple", "stageID", chi.URLParam(r, "stageID"), &stageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stageID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStagesStageIDPerformancesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStagesStageIDPerformances(w, r, stageID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostStagesStageIDPerformances operation middleware
func (siw *ServerInterfaceWrapper) PostStagesStageIDPerformances(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "stageID" -------------
	var stageID string

	err = runtime.BindStyledParameterWithOptions("simple", "stageID", chi.URLParam(r, "stageID"), &stageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stageID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostStagesStageIDPerformances(w, r, stageID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutStagesStageIDPerformances operation middleware
func (siw *ServerInterfaceWrapper) PutStagesStageIDPerformances(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "stageID" -------------
	var stageID string

	err = runtime.BindStyledParameterWithOptions("simple", "stageID", chi.URLParam(r, "stageID"), &stageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stageID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutStagesStageIDPerformances(w, r, stageID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUsersUserID(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersUserID(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUsersUserID(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/participations/slams/{slamID}", wrapper.DeleteParticipationsSlamsSlamID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/participations/slams/{slamID}", wrapper.PostParticipationsSlamsSlamID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/participations/slams/{slamID}/users", wrapper.GetParticipationsSlamsSlamIDUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/participations/slams/{slamID}/users", wrapper.PostParticipationsSlamsSlamIDUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/participations/slams/{slamID}/users/{userID}", wrapper.DeleteParticipationsSlamsSlamIDUsersUserID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/participations/slams/{slamID}/users/{userID}", wrapper.PutParticipationsSlamsSlamIDUsersUserID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/participations/users/{userID}/slams", wrapper.GetParticipationsUsersUserIDSlams)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/performances/{performanceID}", wrapper.DeletePerformancesPerformanceID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/performances/{performanceID}", wrapper.GetPerformancesPerformanceID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/performances/{performanceID}", wrapper.PutPerformancesPerformanceID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/performances/{performanceID}/votes", wrapper.GetPerformancesPerformanceIDVotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/performances/{performanceID}/votes", wrapper.PostPerformancesPerformanceIDVotes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/slams", wrapper.GetSlams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/slams", wrapper.PostSlams)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/slams/{slamID}", wrapper.DeleteSlamsSlamID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/slams/{slamID}", wrapper.GetSlamsSlamID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/slams/{slamID}", wrapper.PutSlamsSlamID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/slams/{slamID}/stages", wrapper.GetSlamsSlamIDStages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/slams/{slamID}/stages", wrapper.PostSlamsSlamIDStages)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/stages/{stageID}", wrapper.DeleteStagesStageID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stages/{stageID}", wrapper.GetStagesStageID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/stages/{stageID}", wrapper.PutStagesStageID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stages/{stageID}/performances", wrapper.GetStagesStageIDPerformances)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/stages/{stageID}/performances", wrapper.PostStagesStageIDPerformances)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/stages/{stageID}/performances", wrapper.PutStagesStageIDPerformances)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.PostUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{userID}", wrapper.DeleteUsersUserID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{userID}", wrapper.GetUsersUserID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{userID}", wrapper.PutUsersUserID)
	})

	return r
}
