// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ParticipationRoleEnum.
const (
	Creator   ParticipationRoleEnum = "creator"
	Performer ParticipationRoleEnum = "performer"
)

// Defines values for StageTypeEnum.
const (
	Battle StageTypeEnum = "battle"
	Simple StageTypeEnum = "simple"
)

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	UserId *string `json:"userId,omitempty"`
	Token  *string `json:"token,omitempty"`
}

// Participation defines model for Participation.
type Participation struct {
	Id   *string                `json:"id,omitempty"`
	Role *ParticipationRoleEnum `json:"role,omitempty"`
}

// ParticipationRequest defines model for ParticipationRequest.
type ParticipationRequest struct {
	UserId *string                `json:"userId,omitempty"`
	Role   *ParticipationRoleEnum `json:"role,omitempty"`
}

// ParticipationRoleEnum defines model for ParticipationRoleEnum.
type ParticipationRoleEnum string

// ParticipationUpdateRequest defines model for ParticipationUpdateRequest.
type ParticipationUpdateRequest struct {
	Role *ParticipationRoleEnum `json:"role,omitempty"`
}

// Performance defines model for Performance.
type Performance struct {
	Id                    *string `json:"id,omitempty"`
	SlamPartId            *string `json:"slamPartId,omitempty"`
	StageId               *string `json:"stageId,omitempty"`
	OpponentPerformanceId *string `json:"opponentPerformanceId"`
	Details               *string `json:"details,omitempty"`
}

// PerformanceRequest defines model for PerformanceRequest.
type PerformanceRequest struct {
	SlamPartId            string  `json:"slamPartId"`
	OpponentPerformanceId *string `json:"opponentPerformanceId"`
	Details               string  `json:"details"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// Slam defines model for Slam.
type Slam struct {
	Id          *string `json:"id,omitempty"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Location    *string `json:"location,omitempty"`
	Public      bool    `json:"public"`
}

// SlamRequest defines model for SlamRequest.
type SlamRequest struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Location    *string `json:"location,omitempty"`
	Public      bool    `json:"public"`
}

// Stage defines model for Stage.
type Stage struct {
	Id        *string        `json:"id,omitempty"`
	SlamId    *string        `json:"slamId,omitempty"`
	Details   *string        `json:"details,omitempty"`
	Round     *int           `json:"round,omitempty"`
	StageType *StageTypeEnum `json:"stageType,omitempty"`
}

// StageRequest defines model for StageRequest.
type StageRequest struct {
	Details   *string       `json:"details,omitempty"`
	Round     *int          `json:"round,omitempty"`
	StageType StageTypeEnum `json:"stageType"`
}

// StageTypeEnum defines model for StageTypeEnum.
type StageTypeEnum string

// User defines model for User.
type User struct {
	Id    *string `json:"id,omitempty"`
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// Vote defines model for Vote.
type Vote struct {
	Id                *string `json:"id,omitempty"`
	PerformanceId     *string `json:"performanceId,omitempty"`
	UserIp            *string `json:"userIp,omitempty"`
	DeviceFingerprint *string `json:"deviceFingerprint,omitempty"`
}

// VoteRequest defines model for VoteRequest.
type VoteRequest struct {
	DeviceFingerprint string `json:"deviceFingerprint"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostParticipationsSlamsSlamIDUsersJSONRequestBody defines body for PostParticipationsSlamsSlamIDUsers for application/json ContentType.
type PostParticipationsSlamsSlamIDUsersJSONRequestBody = ParticipationRequest

// PutParticipationsSlamsSlamIDUsersUserIDJSONRequestBody defines body for PutParticipationsSlamsSlamIDUsersUserID for application/json ContentType.
type PutParticipationsSlamsSlamIDUsersUserIDJSONRequestBody = ParticipationUpdateRequest

// PutPerformancesPerformanceIDJSONRequestBody defines body for PutPerformancesPerformanceID for application/json ContentType.
type PutPerformancesPerformanceIDJSONRequestBody = VoteRequest

// PostPerformancesPerformanceIDVotesJSONRequestBody defines body for PostPerformancesPerformanceIDVotes for application/json ContentType.
type PostPerformancesPerformanceIDVotesJSONRequestBody = VoteRequest

// PostSlamsJSONRequestBody defines body for PostSlams for application/json ContentType.
type PostSlamsJSONRequestBody = SlamRequest

// PutSlamsSlamIDJSONRequestBody defines body for PutSlamsSlamID for application/json ContentType.
type PutSlamsSlamIDJSONRequestBody = SlamRequest

// PostSlamsSlamIDStagesJSONRequestBody defines body for PostSlamsSlamIDStages for application/json ContentType.
type PostSlamsSlamIDStagesJSONRequestBody = StageRequest

// PutStagesStageIDJSONRequestBody defines body for PutStagesStageID for application/json ContentType.
type PutStagesStageIDJSONRequestBody = StageRequest

// PostStagesStageIDPerformancesJSONRequestBody defines body for PostStagesStageIDPerformances for application/json ContentType.
type PostStagesStageIDPerformancesJSONRequestBody = PerformanceRequest

// PutUsersUserIDJSONRequestBody defines body for PutUsersUserID for application/json ContentType.
type PutUsersUserIDJSONRequestBody = User
