// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ParticipationRoleEnum.
const (
	Creator   ParticipationRoleEnum = "creator"
	Moderator ParticipationRoleEnum = "moderator"
	Performer ParticipationRoleEnum = "performer"
)

// Defines values for StageTypeEnum.
const (
	Battle StageTypeEnum = "battle"
	Rated  StageTypeEnum = "rated"
	Simple StageTypeEnum = "simple"
)

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	UserId *string `json:"userId,omitempty"`
	Token  *string `json:"token,omitempty"`
}

// PageNum defines model for PageNum.
type PageNum = int

// PageSize defines model for PageSize.
type PageSize = int

// PaginationObject defines model for PaginationObject.
type PaginationObject struct {
	Page     *int `json:"page,omitempty"`
	PageSize *int `json:"pageSize,omitempty"`
}

// Participation defines model for Participation.
type Participation struct {
	Id     string                `gorm:"primaryKey" json:"id"`
	Role   ParticipationRoleEnum `json:"role"`
	UserId string                `json:"userId"`
	SlamId string                `json:"slamId"`
	Slam   *Slam                 `gorm:"foreignKey:SlamId;references:Id" json:"slam,omitempty"`
	Stages *[]Stage              `gorm:"many2many:performances" json:"stages,omitempty"`
	User   *User                 `gorm:"foreignKey:UserId;references:Id" json:"user,omitempty"`
}

// ParticipationPagination defines model for ParticipationPagination.
type ParticipationPagination struct {
	Page     *int             `json:"page,omitempty"`
	PageSize *int             `json:"pageSize,omitempty"`
	Items    *[]Participation `json:"items,omitempty"`
}

// ParticipationRequest defines model for ParticipationRequest.
type ParticipationRequest struct {
	UserId string                 `json:"userId"`
	Role   *ParticipationRoleEnum `json:"role,omitempty"`
}

// ParticipationRoleEnum defines model for ParticipationRoleEnum.
type ParticipationRoleEnum string

// ParticipationUpdateRequest defines model for ParticipationUpdateRequest.
type ParticipationUpdateRequest struct {
	Role *ParticipationRoleEnum `json:"role,omitempty"`
}

// Performance defines model for Performance.
type Performance struct {
	Id                    string         `gorm:"primaryKey" json:"id"`
	ParticipationId       string         `json:"participationId"`
	StageId               string         `json:"stageId"`
	OpponentPerformanceId *string        `json:"opponentPerformanceId"`
	Details               *string        `json:"details,omitempty"`
	Participation         *Participation `gorm:"foreignKey:ParticipationId;references:Id" json:"participation,omitempty"`
	Stage                 *Stage         `gorm:"foreignKey:StageId;references:Id" json:"stage,omitempty"`
}

// PerformancePagination defines model for PerformancePagination.
type PerformancePagination struct {
	Page     *int           `json:"page,omitempty"`
	PageSize *int           `json:"pageSize,omitempty"`
	Items    *[]Performance `json:"items,omitempty"`
}

// PerformanceRequest defines model for PerformanceRequest.
type PerformanceRequest struct {
	ParticipationId       string  `json:"participationId"`
	OpponentPerformanceId *string `json:"opponentPerformanceId"`
	Details               *string `json:"details,omitempty"`
}

// PerformanceUpdateRequest defines model for PerformanceUpdateRequest.
type PerformanceUpdateRequest struct {
	OpponentPerformanceId *string `json:"opponentPerformanceId"`
	Details               *string `json:"details,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// Slam defines model for Slam.
type Slam struct {
	Id          string   `gorm:"primaryKey" json:"id"`
	Title       string   `json:"title"`
	Description *string  `json:"description,omitempty"`
	Location    *string  `json:"location,omitempty"`
	Public      bool     `json:"public"`
	Stages      *[]Stage `gorm:"foreignKey:SlamId" json:"stages,omitempty"`
	Users       *[]User  `gorm:"many2many:participations" json:"users,omitempty"`
}

// SlamPagination defines model for SlamPagination.
type SlamPagination struct {
	Page     *int    `json:"page,omitempty"`
	PageSize *int    `json:"pageSize,omitempty"`
	Items    *[]Slam `json:"items,omitempty"`
}

// SlamRequest defines model for SlamRequest.
type SlamRequest struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Location    *string `json:"location,omitempty"`
	Public      bool    `json:"public"`
}

// Stage defines model for Stage.
type Stage struct {
	Id             string           `gorm:"primaryKey" json:"id"`
	SlamId         string           `json:"slamId"`
	StageType      StageTypeEnum    `json:"stageType"`
	Round          *int             `json:"round,omitempty"`
	Details        *string          `json:"details,omitempty"`
	Participations *[]Participation `gorm:"many2many:performances" json:"participations,omitempty"`
}

// StagePagination defines model for StagePagination.
type StagePagination struct {
	Page     *int     `json:"page,omitempty"`
	PageSize *int     `json:"pageSize,omitempty"`
	Items    *[]Stage `json:"items,omitempty"`
}

// StageRequest defines model for StageRequest.
type StageRequest struct {
	StageType StageTypeEnum `json:"stageType"`
	Round     *int          `json:"round,omitempty"`
	Details   *string       `json:"details,omitempty"`
}

// StageTypeEnum defines model for StageTypeEnum.
type StageTypeEnum string

// User defines model for User.
type User struct {
	Id      string `gorm:"primaryKey" json:"id"`
	Email   string `json:"email"`
	Name    string `json:"name"`
	TmpUser *bool  `gorm:"default:false" json:"tmpUser,omitempty"`
}

// UserPagination defines model for UserPagination.
type UserPagination struct {
	Page     *int    `json:"page,omitempty"`
	PageSize *int    `json:"pageSize,omitempty"`
	Items    *[]User `json:"items,omitempty"`
}

// UserRequest defines model for UserRequest.
type UserRequest struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// Vote defines model for Vote.
type Vote struct {
	Id                string  `gorm:"primaryKey" json:"id"`
	PerformanceId     string  `json:"performanceId"`
	UserIp            *string `json:"userIp,omitempty"`
	DeviceFingerprint *string `json:"deviceFingerprint,omitempty"`
}

// VotePagination defines model for VotePagination.
type VotePagination struct {
	Page     *int    `json:"page,omitempty"`
	PageSize *int    `json:"pageSize,omitempty"`
	Items    *[]Vote `json:"items,omitempty"`
}

// VoteRequest defines model for VoteRequest.
type VoteRequest struct {
	DeviceFingerprint string `json:"deviceFingerprint"`
}

// GetParticipationsSlamsSlamIDUsersParams defines parameters for GetParticipationsSlamsSlamIDUsers.
type GetParticipationsSlamsSlamIDUsersParams struct {
	// Page Page number for pagination
	Page *PageNum `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetParticipationsUsersUserIDSlamsParams defines parameters for GetParticipationsUsersUserIDSlams.
type GetParticipationsUsersUserIDSlamsParams struct {
	// Page Page number for pagination
	Page *PageNum `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetPerformancesPerformanceIDVotesParams defines parameters for GetPerformancesPerformanceIDVotes.
type GetPerformancesPerformanceIDVotesParams struct {
	// Page Page number for pagination
	Page *PageNum `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetSlamsParams defines parameters for GetSlams.
type GetSlamsParams struct {
	// Page Page number for pagination
	Page *PageNum `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetSlamsSlamIDStagesParams defines parameters for GetSlamsSlamIDStages.
type GetSlamsSlamIDStagesParams struct {
	// Page Page number for pagination
	Page *PageNum `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetStagesStageIDPerformancesParams defines parameters for GetStagesStageIDPerformances.
type GetStagesStageIDPerformancesParams struct {
	// Page Page number for pagination
	Page *PageNum `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PutStagesStageIDPerformancesJSONBody defines parameters for PutStagesStageIDPerformances.
type PutStagesStageIDPerformancesJSONBody = []openapi_types.UUID

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Page Page number for pagination
	Page *PageNum `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostParticipationsSlamsSlamIDUsersJSONRequestBody defines body for PostParticipationsSlamsSlamIDUsers for application/json ContentType.
type PostParticipationsSlamsSlamIDUsersJSONRequestBody = ParticipationRequest

// PutParticipationsSlamsSlamIDUsersUserIDJSONRequestBody defines body for PutParticipationsSlamsSlamIDUsersUserID for application/json ContentType.
type PutParticipationsSlamsSlamIDUsersUserIDJSONRequestBody = ParticipationUpdateRequest

// PutPerformancesPerformanceIDJSONRequestBody defines body for PutPerformancesPerformanceID for application/json ContentType.
type PutPerformancesPerformanceIDJSONRequestBody = PerformanceUpdateRequest

// PostPerformancesPerformanceIDVotesJSONRequestBody defines body for PostPerformancesPerformanceIDVotes for application/json ContentType.
type PostPerformancesPerformanceIDVotesJSONRequestBody = VoteRequest

// PostSlamsJSONRequestBody defines body for PostSlams for application/json ContentType.
type PostSlamsJSONRequestBody = SlamRequest

// PutSlamsSlamIDJSONRequestBody defines body for PutSlamsSlamID for application/json ContentType.
type PutSlamsSlamIDJSONRequestBody = SlamRequest

// PostSlamsSlamIDStagesJSONRequestBody defines body for PostSlamsSlamIDStages for application/json ContentType.
type PostSlamsSlamIDStagesJSONRequestBody = StageRequest

// PutStagesStageIDJSONRequestBody defines body for PutStagesStageID for application/json ContentType.
type PutStagesStageIDJSONRequestBody = StageRequest

// PostStagesStageIDPerformancesJSONRequestBody defines body for PostStagesStageIDPerformances for application/json ContentType.
type PostStagesStageIDPerformancesJSONRequestBody = PerformanceRequest

// PutStagesStageIDPerformancesJSONRequestBody defines body for PutStagesStageIDPerformances for application/json ContentType.
type PutStagesStageIDPerformancesJSONRequestBody = PutStagesStageIDPerformancesJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserRequest

// PutUsersUserIDJSONRequestBody defines body for PutUsersUserID for application/json ContentType.
type PutUsersUserIDJSONRequestBody = UserRequest
