# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
openapi: 3.0.3
info:
  title: SlamIt API
  version: 1.0.0
  description: API for managing poetry slams, user accounts, and participation.

servers:
  - url: /api/v1
    description: "Dev"
  - url: /api/v1
    description: "Prod"

tags:
  - name: auth
    description: User registration and login
  - name: users
    description: User management
  - name: slams
    description: Slam management
  - name: stages
    description: Stage management
  - name: performances
    description: performances management
  - name: participations
    description: Slam participation (users joining slams)

paths:
  /auth/register:
    post:
      tags: [auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid input

  /auth/login:
    post:
      tags: [auth]
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400":
          description: Invalid request
        "401":
          description: Unauthorized

  /users:
    get:
      tags: [users]
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/{id}:
    get:
      tags: [users]
      summary: Get a user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: User not found
    put:
      tags: [users]
      summary: Update a user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: Updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags: [users]
      summary: Delete a user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted
        "404":
          description: User not found

  /slams:
    get:
      tags: [slams]
      summary: Get all slams
      responses:
        "200":
          description: List of slams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Slam'
    post:
      tags: [slams]
      summary: Create a slam
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Slam'
      responses:
        "201":
          description: Slam created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Slam'

  /slams/{id}:
    get:
      tags: [slams]
      summary: Get slam by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A slam
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Slam'
        "404":
          description: Slam not found
    put:
      tags: [slams]
      summary: Update a slam
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Slam'
      responses:
        "200":
          description: Updated slam
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Slam'
    delete:
      tags: [slams]
      summary: Delete a slam
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Deleted
        "404":
          description: Slam not found
          
  /slams/{slamID}/stages:
    get:
      tags: [slams]
      summary: List stages for a slam
      parameters:
        - name: slamID
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of stages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stage'

    post:
      tags: [slams]
      summary: Create a new stage for a slam
      security:
        - bearerAuth: []
      parameters:
        - name: slamID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StageRequest'
      responses:
        "201":
          description: Stage created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stage'

  /stages/{stageID}:
    put:
      tags: [stages]
      summary: Update stage
      parameters:
        - name: stageID
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StageRequest'
      responses:
        "200":
          description: Updated slam
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stage'

  /stages/{stageID}/performances:
    get:
      tags: [stages]
      summary: List performances for a stage
      parameters:
        - name: stageID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of performances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Performance'

    post:
      tags: [stages]
      summary: Add a performance to a stage
      security:
        - bearerAuth: []
      parameters:
        - name: stageID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerformanceRequest'
      responses:
        "201":
          description: Performance created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'

  /performances/{performanceID}:
    put:
      tags: [performances]
      summary: Update a performance
      parameters:
        - name: performanceID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteRequest'
      responses:
        "201":
          description: Vote recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'

  /performances/{performanceID}/votes:
    post:
      tags: [performances]
      summary: Cast a vote for a performance
      parameters:
        - name: performanceID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteRequest'
      responses:
        "201":
          description: Vote recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'

  /participations/users/{userID}/slams/{slamID}:
    post:
      tags: [participations]
      summary: Join a slam
      security:
        - bearerAuth: []
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string
        - name: slamID
          in: path
          required: true
          schema:
            type: integer
      responses:
        "201":
          description: Joined slam
    delete:
      tags: [participations]
      summary: Leave a slam
      security:
        - bearerAuth: []
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string
        - name: slamID
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Left slam

  /participations/users/{userID}/slams:
    get:
      tags: [participations]
      summary: Get slams for a user
      security:
        - bearerAuth: []
      parameters:
        - name: userID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of slams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Slam'

  /participations/slams/{slamID}/users:
    get:
      tags: [participations]
      summary: Get users for a slam
      security:
        - bearerAuth: []
      parameters:
        - name: slamID
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          x-order: 1
        email:
          type: string
          x-order: 2
        name:
          type: string

    Slam:
      type: object
      required: [title, public]
      properties:
        id:
          type: integer
          x-order: 1
        title:
          type: string
          x-order: 2
        description:
          type: string
        location:
          type: string
        public:
          type: boolean

    RegisterRequest:
      type: object
      required: [name, email, password]
      properties:
        email:
          type: string
          x-order: 1
        name:
          type: string
          x-order: 2
        password:
          type: string
      example:
        email: bob@example.com
        name: Bob
        password: P@ssw0rd

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: bob@example.com
        password: P@ssw0rd

    LoginResponse:
      type: object
      properties:
        userId:
          type: string
          x-order: 1
        token:
          type: string
          x-order: 2
    
    Stage:
      type: object
      properties:
        id:
          type: string
        slamId:
          type: integer
        stageType:
          $ref: '#/components/schemas/StageTypeEnum'
        round:
          type: integer
        details:
          type: string

    StageRequest:
      type: object
      required: [stageType]
      properties:
        stageType:
          $ref: '#/components/schemas/StageTypeEnum'
        round:
          type: integer
        details:
          type: string

    Performance:
      type: object
      properties:
        id:
          type: string
        stageId:
          type: integer
        slamPartId:
          type: integer
        opponentPerformanceId:
          type: integer
          nullable: true
        details:
          type: string

    PerformanceRequest:
      type: object
      required: [slamPartId, details]
      properties:
        slamPartId:
          type: integer
        opponentPerformanceId:
          type: string
          nullable: true
        details:
          type: string

    Vote:
      type: object
      properties:
        id:
          type: string
        performanceId:
          type: string
        userIp:
          type: string
        deviceFingerprint:
          type: string

    VoteRequest:
      type: object
      required: [deviceFingerprint]
      properties:
        deviceFingerprint:
          type: string
    
    StageTypeEnum:
      type: string
      enum: 
        - simple
        - battle
